### ISSUE TITLE
Keine Informationen werden übermittelt

### ISSUE THREAD

**Issue by Eidolf** [FaserF/ha-keyforsteam#1]
### The problem

Nach dem hinzufügen der ID bekommt der Sensor keine Information über das Spiel.
Sensor bleibt auf Unbekannt ohne Preisinformation.
Spiel = 163873 = Kingdom Come Deliverance 2

### What version of Home Assistant Core has the issue?

2024.12.2

### What version of keyforsteam Integration has the issue?

1.0.1

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

Logger: homeassistant
Quelle: custom_components/keyforsteam/sensor.py:208
Integration: KeyforSteam (Dokumentation, Probleme)
Erstmals aufgetreten: 12. Dezember 2024 um 19:03:56 (1734 Vorkommnisse)
Zuletzt protokolliert: 09:30:26

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1055, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 978, in async_update_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/keyforsteam/sensor.py", line 117, in state
    cheapest_offer = self._find_cheapest_offer(offers)
  File "/config/custom_components/keyforsteam/sensor.py", line 208, in _find_cheapest_offer
    'coupon': lowest_offer.get('price', {}).get('eur', {}).get('bestCoupon', {}).get('code'),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

### Additional information

_No response_

**Comment by FaserF** [comment]
Ich konnte den Fehler auf meinem System nicht reproduzieren, aber anhand des Logs von dir habe ich einen potentiellen Fehler gefunden. Bitte probier es nun nochmal mit [Version 1.0.2](https://github.com/FaserF/ha-keyforsteam/releases/tag/1.0.2).
